version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
       POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
       POSTGRES_DB: app
       POSTGRES_USER: app
       POSTGRES_PASSWORD: password





